### ISSUE TITLE
preview usage is hard to understand.

### ISSUE THREAD

**Issue by NicolasMICAUX** [RealOrangeOne/zoloto#314]
Hi,
I looked at the args in [this file](https://github.com/RealOrangeOne/zoloto/blob/1613c8a4ec73168646b613982eec4c2f3ccc8440/zoloto/cli/preview.py)
I then used this command: `zoloto preview --type ARUCO_ORIGINAL --id 0`  

It throws this kind of errors:  
```
Traceback (most recent call last):
  File "xxxxx/.venv/lib/python3.10/site-packages/zoloto/cameras/base.py", line 28, in __init__
    self.detector_params = self.get_detector_params()
  File "xxxxx/.venv/lib/python3.10/site-packages/zoloto/cameras/base.py", line 35, in get_detector_params
    return cv2.aruco.DetectorParameters_create()
AttributeError: module 'cv2.aruco' has no attribute 'DetectorParameters_create'. Did you mean: 'DetectorParameters'?
Exception ignored in: <function BaseCamera.__del__ at 0x7f20d53f3e20>
Traceback (most recent call last):
  File "xxxxx/.venv/lib/python3.10/site-packages/zoloto/cameras/base.py", line 153, in __del__
    self.close()
  File "xxxxx/.venv/lib/python3.10/site-packages/zoloto/cameras/camera.py", line 81, in close
    self.video_capture.release()
AttributeError: 'Camera' object has no attribute 'video_capture'
```

It's hard to understand what I'm doing wrong from the docs

**Comment by RealOrangeOne** [comment]
This looks like a bug, possibly related to the OpenCV version you have installed. What version are you using, and how is it installed?
