### ISSUE TITLE
Add check to see if calibrations file exists.

### ISSUE THREAD

**Issue by trickeydan** [RealOrangeOne/zoloto#32]
We should throw a `FileNotFound` or similar if a calibrations file is given and doesn't exist.

For reference, the current error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dan/Code/j5/j5/components/marker_camera.py", line 54, in see
    return self._backend.get_visible_markers(self._identifier)
  File "/home/dan/Code/j5/j5/backends/hardware/zoloto/camera_board.py", line 76, in get_visible_markers
    zmarker.cartesian.x,
  File "/home/dan/.cache/pypoetry/virtualenvs/j5-py3.6/src/zoloto/zoloto/marker.py", line 63, in cartesian
    return ThreeDCoordinates(*self._tvec)
  File "/home/dan/.cache/pypoetry/virtualenvs/j5-py3.6/src/zoloto/zoloto/marker.py", line 85, in _tvec
    _, tvec = self._get_pose_vectors()
  File "/home/dan/.cache/pypoetry/virtualenvs/j5-py3.6/src/zoloto/zoloto/marker.py", line 74, in _get_pose_vectors
    [self.__pixel_corners], self.__size, *self.__camera_calibration_params
cv2.error: OpenCV(4.1.0) /io/opencv/modules/calib3d/src/calibration.cpp:1070: error: (-215:Assertion failed) CV_IS_MAT(objectPoints) && CV_IS_MAT(imagePoints) && CV_IS_MAT(A) && CV_IS_MAT(rvec) && CV_IS_MAT(tvec) in function 'cvFindExtrinsicCameraParams2'
```

**Comment by trickeydan** [comment]
Fixed in 8b94f16
